; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = env1

[env:env1]
lib_deps = 
	alfredosystems/PestoLink-Receive@^1.0.10
	alfredosystems/Alfredo-NoU3@1.0.12
	adafruit/Adafruit BusIO@^1.17.4
	dlloydev/QuickPID@^3.1.9
	dlloydev/sTune@^2.4.0
	hideakitai/VectorXf@^0.1.0
lib_ldf_mode = deep+ 
platform = espressif32
board = NoU3
framework = arduino
monitor_speed = 115200
board_build.variants_dir = variants
board_build.variant = NoU3
